/**
 * Writes out/_headers: the response headers a static host should send (docs/DEPLOY.md). Netlify and
 * Cloudflare Pages read this file as it is; other hosts need the same values in their own syntax.
 *
 * The pages carry their own Content Security Policy in a <meta> (scripts/csp.mjs). Two things a meta
 * policy can't do are here instead: `frame-ancestors`, which browsers ignore in a meta tag, and telling
 * caches to revalidate the service worker on every deploy.
 *
 * `/opengraph-image` is the share-card PNG Next exports with no file extension, so a host that picks a
 * type from the extension has nothing to go on: Cloudflare Pages served it as application/octet-stream
 * on the first launch (docs/DECISIONS.md D-073), which link-preview crawlers can reject and which a
 * browser refuses to draw as an image once `nosniff` is on.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const headers = `# Generated by scripts/headers.mjs; see docs/DEPLOY.md.
/*
  Content-Security-Policy: frame-ancestors 'none'
  X-Content-Type-Options: nosniff
  Referrer-Policy: no-referrer
  Permissions-Policy: geolocation=(), camera=(), microphone=(), interest-cohort=()

/sw.js
  Cache-Control: no-cache

/manifest.webmanifest
  Cache-Control: public, max-age=3600

/opengraph-image
  Content-Type: image/png

/_next/static/*
  Cache-Control: public, max-age=31536000, immutable
`;

writeFileSync(join(import.meta.dirname, "..", "out", "_headers"), headers);
console.log("headers: out/_headers written");
