/**
 * Writes out/sw.js, the service worker that makes the whole static site work offline (BRIEF §10). Runs
 * after `next build`, segments.mjs and csp.mjs, so it precaches exactly the files that will be deployed.
 *
 * - Every file in out/ is precached at install (pages as their URLs, "/learn/" for learn/index.html),
 *   except the worker itself and the development-only /lab page.
 * - The cache name carries a hash of every file's contents, so any change makes a new worker. It installs
 *   in the background and takes over when no tab still runs the old one; the old cache is then deleted.
 * - Requests are answered from this version's cache first (query strings ignored, for Next's `?_rsc=`
 *   payload fetches), then the network. An offline navigation to an unknown page gets the 404 page.
 */
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const outDir = join(import.meta.dirname, "..", "out");

function files(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? files(path) : [path];
  });
}

const entries = files(outDir)
  .map((path) => ({ path, rel: relative(outDir, path).split(sep).join("/") }))
  .filter(({ rel }) => rel !== "sw.js" && !rel.startsWith("lab/") && !rel.endsWith(".map"))
  .sort((a, b) => (a.rel < b.rel ? -1 : 1));

const version = createHash("sha256");
const urls = entries.map(({ path, rel }) => {
  version.update(rel).update(createHash("sha256").update(readFileSync(path)).digest());
  if (rel === "index.html") return "/";
  if (rel.endsWith("/index.html")) return `/${rel.slice(0, -"index.html".length)}`;
  return `/${rel}`;
});
const hash = version.digest("hex").slice(0, 16);

const worker = `// Generated by scripts/sw.mjs; do not edit.
const CACHE = "bldokja-${hash}";
const PRECACHE = ${JSON.stringify(urls)};

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE.map((url) => new Request(url, { cache: "reload" })))));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key.startsWith("bldokja-") && key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET" && request.method !== "HEAD") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith(respond(request, url));
});

async function respond(request, url) {
  const cache = await caches.open(CACHE);
  // Pages are exported with trailing slashes; "/learn" is the same page as "/learn/".
  const last = url.pathname.split("/").pop() ?? "";
  const path = url.pathname.endsWith("/") || last.includes(".") ? url.pathname : url.pathname + "/";
  const cached = await cache.match(path, { ignoreSearch: true });
  if (cached !== undefined) return request.method === "HEAD" ? new Response(null, { status: cached.status, headers: cached.headers }) : cached;
  try {
    return await fetch(request);
  } catch (error) {
    if (request.mode === "navigate") {
      const notFound = await cache.match("/404.html");
      if (notFound !== undefined) return notFound;
    }
    throw error;
  }
}
`;
writeFileSync(join(outDir, "sw.js"), worker);
console.log(`sw: ${urls.length} files precached, cache bldokja-${hash}`);
