import {
  createRng,
  datasetSwap,
  demonstrateSetup,
  pieceType,
  randomMoveSequence,
  trace,
  verifiedMoves,
  type OpSetupsDataset,
  type Puzzle,
  type Rng,
  type Scheme,
  type TraceResult,
} from "@bld/cube-engine";

/**
 * Checkpoint items, generated by the engine so every answer is computed, never typed in. Items are
 * seeded: the same lesson, checkpoint and attempt give the same set.
 */
export type PieceKind = "corners" | "edges";

export type CheckpointItem =
  | { readonly kind: "letter"; readonly pieceType: PieceKind; readonly sticker: string; readonly answer: string }
  | { readonly kind: "trace"; readonly pieceType: PieceKind; readonly buffer: string; readonly scramble: string; readonly answer: readonly string[] }
  | { readonly kind: "parity"; readonly scramble: string; readonly buffers: { readonly corners: string; readonly edges: string }; readonly answer: boolean }
  | { readonly kind: "setup"; readonly pieceType: PieceKind; readonly target: string; readonly letter: string };

/** What a generated trace must look like. */
export type TraceRequirement = "no-breaks" | "break" | "twist" | "any";

export interface ItemContext {
  readonly puzzle: Puzzle;
  readonly scheme: Scheme;
  readonly buffers: { readonly corners: string; readonly edges: string };
}

const FACE_TURNS = (puzzle: Puzzle) => verifiedMoves(puzzle.id).filter((m) => /^[UDRLFB]['2]?$/.test(m));

function meets(t: TraceResult, requires: TraceRequirement, maxTargets: number): boolean {
  if (t.targetCount === 0 || t.targetCount > maxTargets) return false;
  const breaks = t.cycles.some((c) => c.kind === "break");
  const twists = t.cycles.some((c) => c.kind === "orientation");
  if (requires === "no-breaks") return !breaks && !twists;
  if (requires === "break") return breaks && !twists;
  if (requires === "twist") return twists;
  return true;
}

/** A face-turn scramble whose trace for this piece type meets the requirement (bounded search; throws if none is found). */
export function scrambleFor(ctx: ItemContext, rng: Rng, pieceKind: PieceKind, requires: TraceRequirement, maxTargets: number): { scramble: string; traced: TraceResult } {
  const moves = FACE_TURNS(ctx.puzzle);
  for (let attempt = 0; attempt < 4000; attempt++) {
    const length = 3 + rng.int(6);
    const scramble = randomMoveSequence(rng, moves, length).join(" ");
    const traced = trace(ctx.puzzle, { alg: scramble }, { pieceType: pieceKind, buffer: ctx.buffers[pieceKind], scheme: ctx.scheme, policy: { orientedInPlace: "asTargets" } });
    if (traced.ok && meets(traced.value, requires, maxTargets)) return { scramble, traced: traced.value };
  }
  throw new Error(`no scramble with ${requires} and at most ${maxTargets} ${pieceKind} targets`);
}

export function letterItems(ctx: ItemContext, rng: Rng, pieceKinds: readonly PieceKind[], count: number): CheckpointItem[] {
  const pool = pieceKinds.flatMap((kind) =>
    pieceType(ctx.puzzle, kind).stickers.flatMap((s) => {
      const letter = ctx.scheme.letters[kind]?.[s.name];
      return letter === undefined || letter === "" ? [] : [{ kind: "letter" as const, pieceType: kind, sticker: s.name, answer: letter }];
    }),
  );
  const items: CheckpointItem[] = [];
  const used = new Set<string>();
  while (items.length < Math.min(count, pool.length)) {
    const item = pool[rng.int(pool.length)];
    if (item === undefined || used.has(item.sticker)) continue;
    used.add(item.sticker);
    items.push(item);
  }
  return items;
}

export function traceItems(ctx: ItemContext, rng: Rng, pieceKinds: readonly PieceKind[], count: number, requires: TraceRequirement, maxTargets: number): CheckpointItem[] {
  return Array.from({ length: count }, (_, i) => {
    const kind = pieceKinds[i % pieceKinds.length] ?? "corners";
    const { scramble, traced } = scrambleFor(ctx, rng, kind, requires, maxTargets);
    return { kind: "trace", pieceType: kind, buffer: ctx.buffers[kind], scramble, answer: traced.targets };
  });
}

/** Old Pochmann needs the parity alg exactly when the edge target count is odd (it equals the corner count's parity). */
export function parityItems(ctx: ItemContext, rng: Rng, count: number): CheckpointItem[] {
  return Array.from({ length: count }, () => {
    const { scramble, traced } = scrambleFor(ctx, rng, "corners", "any", 8);
    return { kind: "parity", scramble, buffers: ctx.buffers, answer: traced.parity };
  });
}

export function setupItems(ctx: ItemContext, rng: Rng, dataset: OpSetupsDataset, count: number): CheckpointItem[] {
  const kind = dataset.pieceType;
  const targets = dataset.records.filter((r) => r.setup !== "");
  const items: CheckpointItem[] = [];
  const used = new Set<string>();
  while (items.length < Math.min(count, targets.length)) {
    const record = targets[rng.int(targets.length)];
    if (record === undefined || used.has(record.target)) continue;
    used.add(record.target);
    items.push({ kind: "setup", pieceType: kind, target: record.target, letter: ctx.scheme.letters[kind]?.[record.target] ?? "" });
  }
  return items;
}

export function checkpointRng(lessonId: string, checkpointId: string, attempt: number): Rng {
  return createRng(`${lessonId}#${checkpointId}#${attempt}`);
}

const normalise = (text: string) => text.replace(/[\s,]+/g, "").toLocaleUpperCase("en-GB");

export function gradeLetters(expected: readonly string[] | string, typed: string): boolean {
  return normalise(Array.isArray(expected) ? expected.join("") : (expected as string)) === normalise(typed);
}

/**
 * A setup answer is right if it's legal for the method, not only if it matches the table: it must bring
 * the target to the swap sticker and leave the buffer and the swap's side effect alone, which the
 * engine checks by running setup · swap · undo and comparing the whole cube.
 */
export function gradeSetup(puzzle: Puzzle, dataset: OpSetupsDataset, target: string, typed: string): { correct: boolean; reason: "legal" | "does-not-reach" | "damages" | "unreadable" } {
  const swap = datasetSwap(puzzle, dataset);
  if (!swap.ok) throw new Error("dataset swap failed verification");
  const demo = demonstrateSetup(puzzle, swap.value, referenceSticker(puzzle, dataset), target, typed.trim());
  if (!demo.ok) return { correct: false, reason: "unreadable" };
  if (!demo.value.reachesSwapSticker) return { correct: false, reason: "does-not-reach" };
  if (demo.value.damagedPieces.length > 0) return { correct: false, reason: "damages" };
  return { correct: true, reason: "legal" };
}

function referenceSticker(puzzle: Puzzle, dataset: OpSetupsDataset): string {
  const piece = pieceType(puzzle, dataset.pieceType).pieceByName(dataset.buffer);
  const sticker = piece?.stickers.find((s) => s.isOrientationReference);
  if (sticker === undefined) throw new Error(`no reference sticker on ${dataset.buffer}`);
  return sticker.name;
}
