import { faceletsOf, formatMoves, invertMoves, expandNodes, parseAlg, pieceType, randomMoveSequence, verifiedMoves, type Puzzle, type Rng, type SwapDataset } from "@bld/cube-engine";
import type { FourBldPieces, Reader4x4 } from "@/lib/reader-4x4";
import { centreSession, traceOf } from "./four-bld";

/**
 * Checkpoint items for the 4BLD lessons, generated by the engine so every answer is computed. Items are
 * seeded like the 3BLD ones (checkpoint-items.ts): the same lesson, checkpoint and attempt give the same set.
 *
 * X-centres have more than one right memo, so a traced x-centre memo is graded by walking it: every letter
 * must be one the cube allows at that point, and the walk must end with the centres solved.
 */
export type FourCheckpointItem =
  | { readonly kind: "four-letter"; readonly pieces: FourBldPieces; readonly sticker: string; readonly answer: string }
  | { readonly kind: "four-trace"; readonly pieces: FourBldPieces; readonly buffer: string; readonly scramble: string; readonly answer: readonly string[] }
  | { readonly kind: "four-parity"; readonly pieces: "wings" | "corners"; readonly scramble: string; readonly answer: boolean }
  | { readonly kind: "four-setup"; readonly method: "r2" | "u2"; readonly target: string; readonly letter: string; readonly answer: string };

/** Turns that scramble one piece type quickly, so a checkpoint trace stays short. */
function movesFor(pieces: FourBldPieces | "both"): string[] {
  const all = verifiedMoves("4x4x4");
  if (pieces === "corners") return all.filter((m) => /^[UDRLFB]['2]?$/.test(m));
  if (pieces === "xcenters") return all.filter((m) => /^2[UDRLFB]['2]?$/.test(m));
  return all.filter((m) => /^(?:[UDRLFB]|2[UDRLFB])['2]?$/.test(m));
}

export function fourLetterItems(reader: Reader4x4, rng: Rng, pieces: readonly FourBldPieces[], count: number): FourCheckpointItem[] {
  const pool = pieces.flatMap((p) =>
    pieceType(reader.puzzle, p).stickers.flatMap((s) => {
      const letter = reader.scheme.letters[p]?.[s.name];
      return letter === undefined || letter === "" ? [] : [{ kind: "four-letter" as const, pieces: p, sticker: s.name, answer: letter }];
    }),
  );
  const items: FourCheckpointItem[] = [];
  const used = new Set<string>();
  while (items.length < Math.min(count, pool.length)) {
    const item = pool[rng.int(pool.length)];
    if (item === undefined || used.has(item.sticker)) continue;
    used.add(item.sticker);
    items.push(item);
  }
  return items;
}

/** One right memo for a piece type (for x-centres, the engine's own choice), or undefined if the scramble doesn't trace. */
export function fourMemo(reader: Reader4x4, scramble: string, pieces: FourBldPieces): string[] | undefined {
  if (pieces !== "xcenters") return traceOf(reader, scramble, pieces)?.targets;
  const session = centreSession(reader, scramble);
  if (session === undefined) return undefined;
  const letters: string[] = [];
  for (let step = session.next(); step !== undefined; step = session.next()) {
    const letter = step.letters[0];
    if (letter === undefined || session.answer(letter) === undefined) return undefined;
    letters.push(letter);
  }
  return letters;
}

export function fourTraceItems(reader: Reader4x4, rng: Rng, pieces: readonly FourBldPieces[], count: number, maxTargets: number): FourCheckpointItem[] {
  return Array.from({ length: count }, (_, i) => {
    const kind = pieces[i % pieces.length] ?? "wings";
    for (let attempt = 0; attempt < 4000; attempt++) {
      const scramble = randomMoveSequence(rng, movesFor(kind), 2 + rng.int(4)).join(" ");
      const answer = fourMemo(reader, scramble, kind);
      if (answer !== undefined && answer.length > 0 && answer.length <= maxTargets) return { kind: "four-trace" as const, pieces: kind, buffer: reader.buffers[kind], scramble, answer };
    }
    throw new Error(`no ${kind} scramble with at most ${String(maxTargets)} targets`);
  });
}

export function fourParityItems(reader: Reader4x4, rng: Rng, pieces: readonly ("wings" | "corners")[], count: number): FourCheckpointItem[] {
  return Array.from({ length: count }, (_, i) => {
    const kind = pieces[i % pieces.length] ?? "wings";
    for (let attempt = 0; attempt < 4000; attempt++) {
      const scramble = randomMoveSequence(rng, movesFor("both"), 2 + rng.int(5)).join(" ");
      const traced = traceOf(reader, scramble, kind);
      if (traced !== undefined && traced.targetCount > 0 && traced.targetCount <= 10) return { kind: "four-parity" as const, pieces: kind, scramble, answer: traced.targetStickers.length % 2 === 1 };
    }
    throw new Error(`no ${kind} parity scramble`);
  });
}

export function fourSetupItems(reader: Reader4x4, rng: Rng, dataset: SwapDataset, count: number): FourCheckpointItem[] {
  const pieces = dataset.method === "r2" ? "wings" : "xcenters";
  const targets = dataset.records.filter((r) => r.kind === "target" && r.setup !== "");
  const items: FourCheckpointItem[] = [];
  const used = new Set<string>();
  while (items.length < Math.min(count, targets.length)) {
    const record = targets[rng.int(targets.length)];
    if (record === undefined || record.kind !== "target" || used.has(record.target)) continue;
    used.add(record.target);
    items.push({ kind: "four-setup", method: dataset.method === "r2" ? "r2" : "u2", target: record.target, letter: reader.scheme.letters[pieces]?.[record.target] ?? "", answer: record.setup });
  }
  return items;
}

const letters = (typed: string) => typed.replace(/[\s,]+/g, "").toLocaleUpperCase("en-GB").split("").filter(Boolean);

/** A typed memo: exactly the trace for wings and corners; any walk that solves them for x-centres. */
export function gradeFourMemo(reader: Reader4x4, item: Extract<FourCheckpointItem, { kind: "four-trace" }>, typed: string): boolean {
  const given = letters(typed);
  if (item.pieces !== "xcenters") return given.join("") === item.answer.join("").toLocaleUpperCase("en-GB");
  const session = centreSession(reader, item.scramble);
  if (session === undefined) return false;
  for (const letter of given) if (session.answer(letter) === undefined) return false;
  return session.done;
}

/** Whether two move sequences leave the cube looking the same from solved: exact, except x-centres by colour. */
export function sameLook(puzzle: Puzzle, a: string, b: string): boolean {
  const fa = faceletsOf(puzzle, puzzle.kpuzzle.defaultPattern().applyAlg(a));
  const fb = faceletsOf(puzzle, puzzle.kpuzzle.defaultPattern().applyAlg(b));
  for (let slot = 0; slot < fa.length; slot++) {
    const x = fa[slot] ?? -1;
    const y = fb[slot] ?? -1;
    if (x === y) continue;
    const orbit = puzzle.stickerMap.orbits[puzzle.stickerMap.slotOfSticker[slot]?.orbitIndex ?? -1];
    if (orbit?.interchangeable !== true || puzzle.geometry.sticker(x).face !== puzzle.geometry.sticker(y).face) return false;
  }
  return true;
}

/**
 * A setup is right if it works, not only if it's the table's: setup, swap and undo must do what the
 * verified record does — the target exchanged with the buffer, the swap's side effect, nothing else.
 */
export function gradeFourSetup(puzzle: Puzzle, dataset: SwapDataset, target: string, typed: string): { correct: boolean; reason: "legal" | "wrong-effect" | "unreadable" } {
  const record = dataset.records.find((r) => r.target === target);
  const expected = record?.algs[0]?.moves;
  const parsed = parseAlg(puzzle.id, typed.trim());
  if (!parsed.ok || typed.trim() === "") return { correct: false, reason: "unreadable" };
  if (expected === undefined) return { correct: false, reason: "wrong-effect" };
  const setup = expandNodes(parsed.value.nodes);
  const shot = `${formatMoves(setup)} ${dataset.swap.alg} ${formatMoves(invertMoves(setup))}`;
  return sameLook(puzzle, shot, expected) ? { correct: true, reason: "legal" } : { correct: false, reason: "wrong-effect" };
}
