export const siteGuide = {
  title: "Site guide", welcome: "New here? Find your way around in six short steps.", start: "Show me around", resume: "Resume guide", restart: "Restart guide", previous: "Previous", next: "Next", close: "Close guide", finish: "Finish guide",
  progress: (step: number, total: number) => `Step ${step} of ${total}`, saving: "Saving your place…", error: "Your place could not be saved. Try the action again; this guide stays open.",
  steps: [
    { title: "Learn at your own pace", body: "Start on the learning path. Every lesson is open, prerequisites explain the suggested order, and checkpoints save your progress on this device. You can revisit any section.", href: "/learn/", link: "Open the learning path" },
    { title: "Make the cube work for you", body: "The exact sticker net loads first. Inspect in 3D enables rotation for this session. Algorithms have play and step controls; text view provides a move-by-move alternative. Cube sticker palettes and interface colour themes are separate.", href: "/settings/", link: "Open display settings" },
    { title: "Learn letters, then trace", body: "Speffz recognition shows a complete piece and asks you to name each coloured sticker. Guided trace follows an actual scramble one target at a time. Previous target reviews without repeating a scored attempt. Lessons teach standard buffers; custom trainer buffers are shown explicitly.", href: "/practice/speffz/", link: "Try Speffz recognition" },
    { title: "Practise one skill at a time", body: "Move from recognition to setup recall, full algorithm recall, blind execution and full solves. Save verified personal algorithms and compare them with alternating timed trials. Recognition and execution results are recorded separately.", href: "/practice/", link: "Browse the trainers" },
    { title: "Build your own memo", body: "Use your own letter-pair words and images, reusable memory-palace locations and story sequences. Everything stays in this browser. Export a backup before changing devices or clearing browser storage.", href: "/practice/pairs/", link: "Open letter pairs" },
    { title: "Review, diagnose and work offline", body: "Progress helps you find slow or inaccurate cases; the DNF debugger compares the evidence you provide rather than guessing. Settings includes downloadable references, backups and the offline pack. Updates are announced when available. There are no accounts or server uploads.", href: "/progress/", link: "Open progress" },
  ],
} as const;
